[theme]
primaryColor = "#2E7D32"
backgroundColor = "#F5F5F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#212121"
font = "sans serif"

[server]
enableXsrfProtection = true
enableCORS = false
enableStaticServing = true
staticDirectory = "src/static"

[browser]
gatherUsageStats = false

[runner]
fastRerenderThreshold = 1000 